### ISSUE TITLE
Spreads Covid 19 misinformation

### ISSUE THREAD

**Issue by eutro** [DoctorNight799/Covid-vaccine#1]
As of the time of writing, the vaccine item in this mod immediately cures the user of Covid 19:

https://github.com/DoctorNight799/Covid-vaccine/blob/445d61c26940827149b50714d13dcc0410f6be76/src/main/java/dev/covid/items/VaccineItem.java#L29-L44

(Line 40, specifically)

This is incorrect and does not accurately reflect the behaviour of vaccines in real life.

Vaccines [provide acquired immunity to a disease](https://en.wikipedia.org/wiki/Vaccine#cite_note-iac39-1), rather than immediately curing it.

In its current state, this mod thus spreads Covid 19 misinformation, and I urge that you fix it.

**Comment by DoctorNight799** [comment]
That's a fun/rofl mod for minecraft, and u really ask me to fix this bcs it isn't like in real life? lol
That's not so easy to do, you know.

**Comment by eutro** [comment]
You think this is a joke? Millions of people have fallen ill. Hundreds of thousands of people have died. Millions of people have lost their jobs. Entire companies and businesses have been rendered bankrupt. And you call this a joke? This is incredibly serious, and spreading misinformation is one of the worst things you could do. You should be ashamed of yourself.

**Comment by DoctorNight799** [comment]
Man, this is just a game, it isn't a real life and a from these million of people who fallen ill will just a half and less will fin this mod. And i'm one of them so stop this cringe.

**Comment by Lgmrszd** [comment]
@eutro based and vaccinepilled
